spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: dev_mail_username
    password: dev_mail_password
